#!/usr/bin/env node

// @ts-ignore
BigInt.prototype.toJSON = function() {
  return this.toString();
}

const yargs = require('yargs');

const {list} = require('./list.js');
const {add} = require('./add.js');
const {update} = require('./update.js');
const {remove} = require('./remove.js');
const {merge} = require('./merge.js');
const {diff} = require('./diff.js');
const {apply} = require('./apply.js');
const {config} = require('./config.js');
const {commit} = require('./commit.js');
const {status} = require('./status.js');
const {server} = require('./server.js');
const {remoteAdd, remoteRemove, remoteList, remoteUpdate} = require('./remote.js');

function run(fn) {
  return function(argv) {
    fn(argv).catch(err => {
      console.log('Pismo failed with error:');
      console.log(err);
    });
  }
}

// TODO delet this
const defaultHandler = argv => console.log('Not implemented yet. argv: ' + JSON.stringify(argv, null, 2));

yargs
  .command(
    'list',
    'Lists directory trees stored in ~/.pismo.',
    yargs => yargs
        .help(false)
        .version(false),
    run(list))

  .command(
    'add <name> <path>',
    'Adds a new directory tree to ~/.pismo named <name> and rooted at the filepath <path>.',
    yargs => yargs
        .option('noupdate', {
          description: "Don't run a scan on the new file tree",
          default: false
        })
        .help(false)
        .version(false),
    run(add))

  .command(
    'remove <name>',
    'Removes a directory tree from ~/.pismo named <name>.',
    yargs => yargs
        .help(false)
        .version(false),
    run(remove))

  .command(
    'remote-add <name> <url>',
    'Adds a remote pismo server at the specified url.',
    yargs => yargs
        .positional('name', {
          description: 'new name used to reference the remote.'
        })
        .positional('url', {
          description: 'host URL. ex: http://example.com:48880'
        })
        .help(false)
        .version(false),
    run(remoteAdd))

  .command(
    'remote-remove <name>',
    'Deletes a remote you are currently tracking.',
    yargs => yargs
        .positional('name', {
          description: 'name of the remote to remove.'
        })
        .help(false)
        .version(false),
    run(remoteRemove))

  .command(
    'fetch <name>',
    'Downloads information about all directory trees on remote server.',
    yargs => yargs
        .positional('name', {
          description: 'name of the remote to update.'
        })
        .option('prune', {
          description: 'Delete all local trees no longer on the remote server',
          default: false
        })
        .help(false)
        .version(false),
    run(remoteUpdate))

  .command(
    'remote-list',
    'Lists all of the remotes you are currently tracking.',
    yargs => yargs
        .help(false)
        .version(false),
    run(remoteList))

  .command(
    'update <name>',
    'Runs a scan on the file tree named <name>, updating the state of the tree stored in ~/.pismo',
    yargs => yargs
        .option('nocache', {
          description: 'Recalculate hashes for each file instead of reusing them based on file modified time',
          default: false
        })
        .help(false)
        .version(false),
    run(update))

  .command(
    'diff <base> [other]',
    'Compares the contents of the directory trees named <base> and [other], and prints out the differences. If [other] is unset and backups are enabled, compares between backup and newest version of <base>.',
    yargs => yargs
        .help(false)
        .version(false),
    run(diff))

  .command(
    'merge-gen <base> <other> <output-filepath>',
    'Compares the directory trees named <base> and <other> and writes a merge file to the path <output-filepath>, which can then be applied by using merge-apply.',
    yargs => yargs
        .option('mode', {
          choices: ['one-way-mirror', 'two-way-sync'],
          default: 'one-way-mirror',
          description: 'Preset to generate merge file with'
        })
        .help(false)
        .version(false),
    run(merge))

  .command(
    'merge-apply <mergefile>',
    'Copies and moves files based on the contents in <mergefile>, which is generated by using merge-gen',
    yargs => yargs
        .help(false)
        .version(false),
    run(apply))

  .command(
    'config <setting> [value]',
    'Sets configuration variables stored in ~/.pismo/config.json',
    yargs => yargs
        .help(false)
        .version(false),
    run(config))

  .command(
    'status <name>',
    'Gets observed changes since last commit to file tree named <name>. Does nothing if backups are disabled.',
    yargs => yargs
        .help(false)
        .version(false),
    run(status))

  .command(
    'commit <name>',
    'Commits changes to file tree named <tree>, removing the backup "image" of the file tree. Does nothing if backups are disabled.',
    yargs => yargs
        .help(false)
        .version(false),
    run(commit))

  .command(
    'server [port]',
    'Runs a pismo protocol server so this computer can be synced by a remote client.',
    yargs => yargs
        .positional('port', {
          description: 'port to bind on',
          default: 48880
        })
        .help(false)
        .version(false),
    run(server))

//  .command(
//    'http [port]',
//    'Runs a web interface to use pismo on this computer instead of the cli.',
//    yargs => yargs
//        .positional('port', {
//          description: 'port to bind http server to',
//          default: 48880
//        })
//        .help(false)
//        .version(false),
//    defaultHandler)

  // TODO add global config to change ~/.pismo to custom directory

  .demandCommand()
  .strict()
  // .wrap(Math.min(80, yargs.terminalWidth()) // default
  .wrap(null)
  .argv;
