#!/usr/bin/env node

// TODO delet this
const defaultHandler = argv => console.log('todo handler. argv: ' + JSON.stringify(argv, null, 2));

require('yargs')
  .command(
    'list',
    'Lists directory trees stored in ~/.pismo',
    yargs => yargs
        .help(false)
        .version(false),
    defaultHandler)

  .command(
    'add <name> <path>',
    'Adds a new directory tree to ~/.pismo named <name> and rooted at the filepath <path>',
    yargs => yargs
        .option('noupdate', {
          description: "Don't run a scan on the new file tree",
          default: false
        })
        .help(false)
        .version(false),
    defaultHandler)

  .command(
    'update <name>',
    'Runs a scan on the file tree named <name>, updating the state of the tree stored in ~/.pismo',
    yargs => yargs
        .help(false)
        .version(false),
    defaultHandler)

  .command(
    'diff <base> <other>',
    'Compares the contents of the directory trees named <base> and <other>, and prints out the differences.',
    yargs => yargs
        .help(false)
        .version(false),
    defaultHandler)

  .command(
    'merge-gen <base> <other> <output>',
    'Compares the directory trees named <base> and <other> and writes a merge file to the path <output>, which can then be applied by using merge-apply.',
    yargs => yargs
        .option('mode', {
          choices: ['one-way-mirror', 'two-way-sync'],
          default: 'one-way-mirror',
          description: 'Preset to generate merge file with'
        })
        .help(false)
        .version(false),
    defaultHandler)

  .command(
    'merge-apply <mergefile>',
    'Copies and moves files based on the contents in <mergefile>, which is generated by using merge-gen',
    yargs => yargs
        .help(false)
        .version(false),
    defaultHandler)

  .demandCommand()
  .strict()
  // .wrap(Math.min(80, yargs.terminalWidth()) // default
  .wrap(null)
  .argv;
